RafaelMillis/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RafaelMillis.ViewModel;
using RafaelMillis.QueueEntities;
using RafaelMillis.BLL;

namespace RafaelMillis.Controllers
{
    /// <summary>
    /// Queue WebAPI 
    /// </summary>
    public class QueueController : Controller
    {
        // GET: Queue
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// get active customer which in service
        /// </summary>
        /// <returns></returns>
        public JsonResult ActiveCustomer()
        {
            QueueBLL bll = new QueueBLL();
            List<CustomerView> customer = new List<CustomerView>();
            customer.Add(bll.GetActiveCustomer());
            return Json(customer, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// get customers waiting list
        /// </summary>
        /// <returns></returns>
        public JsonResult WaitingList()
        {
            QueueBLL bll = new QueueBLL();
            List<Customer> custs = bll.GetCustomerWaiting();
            List<CustomerView> custsview = new List<CustomerView>();
            CustomerView tmp;
            foreach (Customer c in custs)
            {
                tmp = new CustomerView { CustomerName = c.FirstName + " " + c.LastName, QueueID = c.QueueID, QueueTime = c.Time.ToShortTimeString() };
                custsview.Add(tmp);
            }
            return Json( custsview, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// get next customer
        /// </summary>
        /// <returns></returns>
        public JsonResult UpdateNextCustomer()
        {
            QueueBLL bll = new QueueBLL();
            bll.UpdateNextCustomer();

            return WaitingList();
        }


        /// <summary>
        /// insert a new customer to the waiting list
        /// </summary>
        /// <param name="firstName"></param>
        /// <param name="lastName"></param>
        /// <returns></returns>
        public JsonResult InsertNewCustomer(string firstName, string lastName)
        {
            Customer cust = new Customer { FirstName = firstName, LastName = lastName, Time = DateTime.Now };
            QueueBLL bll = new QueueBLL();
            bll.InsertNewCustomer(cust);

            return WaitingList();
        }

    }
}

RafaelMillis/Views/Queue/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2></h2>
<br />
<div ng-app="myApp" ng-controller="queueCtrl">
    <div dir="auto">
        <div class="queue-content">
            <label for="fname">שם פרטי</label> <input id="fname" type="text" ng-model="firstName" placeholder="הכנס שם פרטי" required autofocus>
            <label for="lname">שם משפחה</label> <input id="lname" type="text" ng-model="lastName" placeholder="הכנס שם משפחה" required>
            <input id="queueNewCust" type="button" value="הכנס לתור" ng-click="insertNewCustomer()" class="btn-q" />
            <br><br /><br />
            <div class="next-cust">
                <input type="button" value="קרא להבא בתור" ng-click="getNextCustomer()" class="btn-q" />
            </div>
            <br />
            <label for="activeCust" class="label-right">בשירות</label>
            <div id="activeCust" class="active-cust">
                <table class="tbl-queue">
                    <tr ng-repeat="cust in nextCustomer">
                        <td>{{cust.QueueID}}</td>
                        <td>{{cust.CustomerName}}</td>
                        <td>{{cust.QueueTime}}</td>
                    </tr>
                </table>
            </div>
            <br /><br />
            
            <label>רשימת ממתינים</label>
            <div id="tbl-q">
                <table class="tbl-queue">
                    <tr>
                        <th>
                            מספר תור
                        </th>
                        <th>
                            שם לקוח
                        </th>
                        <th>
                            שעת כניסה לתור
                        </th>
                    </tr>
                    <tr ng-repeat="cust in waitList">
                        <td>{{cust.QueueID}}</td>
                        <td>{{cust.CustomerName}}</td>
                        <td>{{cust.QueueTime}}</td>
                    </tr>
                </table>
            </div>
            <br /><br />
        </div>
        <br>
    </div>
</div>


RafaelMillis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Queue Waiting List", "Index", "Queue", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Queue", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/queue")
    @RenderSection("scripts", required: false)
</body>
</html>